# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push: 
    branches : [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout code
        uses: actions/checkout@v3
      
      - name : seup node 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name : run tests
        
        run: |
          npm ci
          npm test
          
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t tic-tac-react:v1 .

      - name: Push Docker Image
        run: docker push summerof98/tic-tac-react:v1


